/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class process_communication_huige_com_myapplication_MainActivity */

#ifndef _Included_process_communication_huige_com_myapplication_MainActivity
#define _Included_process_communication_huige_com_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     process_communication_huige_com_myapplication_MainActivity
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_process_1communication_huige_com_myapplication_MainActivity_sayHello
  (JNIEnv *, jobject, jstring,jboolean);

#ifdef __cplusplus
}
#endif
#endif
